# Generated by Django 2.1.1 on 2018-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A02',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=10, null=True)),
                ('liandata', models.DateTimeField(blank=True, null=True)),
                ('anno', models.CharField(blank=True, max_length=20, null=True)),
                ('executegov', models.CharField(blank=True, max_length=100, null=True)),
                ('biaodi', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=10, null=True)),
                ('partycardnum', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'a02',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
